version: '3.8'
services:
  redis:
    image: 'redis'
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  backend:
    build: ./
    ports:
      - '8000:8000'
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env.development
    depends_on:
      - redis

  consumer:
    build: ./yungizzangzzang-be-consumer
    ports:
      - '8001:8001'
    volumes:
      - ./yungizzangzzang-be-consumer:/app
      - /app/node_modules
    env_file:
      - ./.env.development
    depends_on:
      - redis

volumes:
  redis_data:
