prometheus:
  url: http://prometheus-server.default.svc
rules:
  custom:
    - seriesQuery: '{__name__=~"^node_cpu_seconds_total", mode="idle"}'
      resources:
        template: "<<.Resource>>"
      name:
        matches: "^(.*)_total"
        as: "cpu_idle"
      metricsQuery: 'avg(irate(node_cpu_seconds_total{mode="idle"}[5m])) by (<<.GroupBy>>)'
    - seriesQuery: '{__name__=~"^node_memory_MemTotal_bytes", ...}'
      resources:
        template: "<<.Resource>>"
      name:
        as: "memory_used_ratio"
      metricsQuery: '(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes * 100'