version: '3.8'
services:
  redis:
    image: 'redis'
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  backend1:
    build: ./
    ports:
      - '8001:8001'
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env.development
    depends_on:
      - redis

volumes:
  redis_data:
