name: Build and Push to Docker Hub

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build, tag, and push image to Docker Hub
        env:
          DOCKERHUB_REPOSITORY: whdgnszz1/last-bite-backend
          IMAGE_TAG: ${{ steps.get-latest-commit-hash.outputs.commit-hash }}
        run: |
          docker build -t $DOCKERHUB_REPOSITORY:$IMAGE_TAG .
          docker push $DOCKERHUB_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$DOCKERHUB_REPOSITORY:$IMAGE_TAG"
