name: Deploy to Amazon EKS and Docker Hub

on:
  push:
    branches:
      - dev

env:
  AWS_REGION: ap-northeast-2
  DOCKER_REPOSITORY: last-bite-backend
  K8S_NAMESPACE: default
  K8S_DEPLOYMENT_NAME: last-bite-deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Build and tag image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_REPOSITORY }}:${{ github.sha }} .

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push to Docker Hub
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_REPOSITORY }}:${{ github.sha }}

    - name: Install and configure kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml

    - name: Deploy to EKS
      run: |
        kubectl set image deployment/${{ env.K8S_DEPLOYMENT_NAME }} last-bite-api=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_REPOSITORY }}:${{ github.sha }} --namespace=${{ env.K8S_NAMESPACE }} --kubeconfig=kubeconfig.yaml
